const CREATE_INVITE_REQUEST = "@app/invite/CREATE_INVITE_REQUEST";
const CREATE_INVITE_SUCCESS = "@app/invite/CREATE_INVITE_SUCCESS";
const CREATE_INVITE_FAILURE = "@app/invite/CREATE_INVITE_FAILURE";

const FETCH_INVITES_SUCCESS = "@app/invite/FETCH_INVITES_SUCCESS";

export const invitesTypes = {
  CREATE_INVITE_REQUEST,
  CREATE_INVITE_SUCCESS,
  CREATE_INVITE_FAILURE,

  FETCH_INVITES_SUCCESS
};
