const CREATE_INVITE_REQUEST = "@app/invite/CREATE_INVITE_REQUEST";
const CREATE_INVITE_SUCCESS = "@app/invite/CREATE_INVITE_SUCCESS";
const CREATE_INVITE_FAILURE = "@app/invite/CREATE_INVITE_FAILURE";

const FETCH_INVITES_SUCCESS = "@app/invite/FETCH_INVITES_SUCCESS";

const OPEN_INVITE = "@app/invite/OPEN_INVITE";
const CLOSE_INVITE = "@app/invite/CLOSE_INVITE";

export const invitesTypes = {
  CREATE_INVITE_REQUEST,
  CREATE_INVITE_SUCCESS,
  CREATE_INVITE_FAILURE,

  FETCH_INVITES_SUCCESS,

  OPEN_INVITE,
  CLOSE_INVITE
};
