const CREATE_LEAGUE_REQUEST = "@app/league/CREATE_LEAGUE_REQUEST";
const CREATE_LEAGUE_SUCCESS = "@app/league/CREATE_LEAGUE_SUCCESS";
const CREATE_LEAGUE_FAILURE = "@app/league/CREATE_LEAGUE_FAILURE";

const FETCH_LEAGUES_REQUEST = "@app/league/FETCH_LEAGUES_REQUEST";
const FETCH_LEAGUES_SUCCESS = "@app/league/FETCH_LEAGUES_SUCCESS";
const FETCH_LEAGUES_FAILURE = "@app/league/FETCH_LEAGUES_FAILURE";

const UPDATE_LEAGUE_REQUEST = "@app/LEAGUE/UPDATE_LEAGUE_REQUEST";
const UPDATE_LEAGUE_SUCCESS = "@app/LEAGUE/UPDATE_LEAGUE_SUCCESS";
const UPDATE_LEAGUE_FAILURE = "@app/LEAGUE/UPDATE_LEAGUE_FAILURE";

const OPEN_CREATE_LEAGUE = "@app/LEAGUE/OPEN_CREATE_LEAGUE";
const CLOSE_CREATE_LEAGUE = "@app/LEAGUE/CLOSE_CREATE_LEAGUE";

export const leagueTypes = {
  CREATE_LEAGUE_REQUEST,
  CREATE_LEAGUE_SUCCESS,
  CREATE_LEAGUE_FAILURE,

  FETCH_LEAGUES_FAILURE,
  FETCH_LEAGUES_REQUEST,
  FETCH_LEAGUES_SUCCESS,

  UPDATE_LEAGUE_REQUEST,
  UPDATE_LEAGUE_SUCCESS,
  UPDATE_LEAGUE_FAILURE,

  OPEN_CREATE_LEAGUE,
  CLOSE_CREATE_LEAGUE
};
