const CREATE_LEAGUE_REQUEST = "@app/league/CREATE_LEAGUE_REQUEST";
const CREATE_LEAGUE_SUCCESS = "@app/league/CREATE_LEAGUE_SUCCESS";
const CREATE_LEAGUE_FAILURE = "@app/league/CREATE_LEAGUE_FAILURE";

const CREATE_GAME_REQUEST = "@app/league/CREATE_GAME_REQUEST";
const CREATE_GAME_SUCCESS = "@app/league/CREATE_GAME_SUCCESS";
const CREATE_GAME_FAILURE = "@app/league/CREATE_GAME_FAILURE";

const FETCH_LEAGUES_REQUEST = "@app/league/FETCH_LEAGUES_REQUEST";
const FETCH_LEAGUES_SUCCESS = "@app/league/FETCH_LEAGUES_SUCCESS";
const FETCH_LEAGUES_FAILURE = "@app/league/FETCH_LEAGUES_FAILURE";

export const leagueTypes = {
  CREATE_LEAGUE_REQUEST,
  CREATE_LEAGUE_SUCCESS,
  CREATE_LEAGUE_FAILURE,
  CREATE_GAME_REQUEST,
  CREATE_GAME_SUCCESS,
  CREATE_GAME_FAILURE,
  FETCH_LEAGUES_FAILURE,
  FETCH_LEAGUES_REQUEST,
  FETCH_LEAGUES_SUCCESS
};
