const LOGIN_REQUEST = "@app/user/LOGIN_REQUEST";
const LOGIN_SUCCESS = "@app/user/LOGIN_SUCCESS";
const LOGIN_FAILURE = "@app/user/LOGIN_FAILURE";

const REGISTER_REQUEST = "@app/user/REGISTER_REQUEST";
const REGISTER_SUCCESS = "@app/user/REGISTER_SUCCESS";
const REGISTER_FAILURE = "@app/user/REGISTER_FAILURE";

const RECOVER_REQUEST = "@app/user/RECOVER_REQUEST";
const RECOVER_SUCCESS = "@app/user/RECOVER_SUCCESS";
const RECOVER_FAILURE = "@app/user/RECOVER_FAILURE";

const COMPLETE_RECOVER_REQUEST = "@app/user/COMPLETE_RECOVER_REQUEST";
const COMPLETE_RECOVER_SUCCESS = "@app/user/COMPLETE_RECOVER_SUCCESS";
const COMPLETE_RECOVER_FAILURE = "@app/user/COMPLETE_RECOVER_FAILURE";

const LOGOUT_REQUEST = "@app/user/LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "@app/user/LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "@app/user/LOGOUT_FAILURE";

const RETREIVE_PROFILE = "@app/user/RETREIVE_PROFILE";

export const userTypes = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,

  RECOVER_REQUEST,
  RECOVER_SUCCESS,
  RECOVER_FAILURE,

  COMPLETE_RECOVER_REQUEST,
  COMPLETE_RECOVER_SUCCESS,
  COMPLETE_RECOVER_FAILURE,

  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,

  RETREIVE_PROFILE
};
