const CREATE_CLUB_REQUEST = "@app/club/CREATE_CLUB_REQUEST";
const CREATE_CLUB_SUCCESS = "@app/club/CREATE_CLUB_SUCCESS";
const CREATE_CLUB_FAILURE = "@app/club/CREATE_CLUB_FAILURE";

export const clubTypes = {
  CREATE_CLUB_REQUEST,
  CREATE_CLUB_SUCCESS,
  CREATE_CLUB_FAILURE
};
