const CREATE_GAME_REQUEST = "@app/games/CREATE_GAME_REQUEST";
const CREATE_GAME_SUCCESS = "@app/games/CREATE_GAME_SUCCESS";
const CREATE_GAME_FAILURE = "@app/games/CREATE_GAME_FAILURE";

const FETCH_GAMES_REQUEST = "@app/games/FETCH_GAMES_REQUEST";
const FETCH_GAMES_SUCCESS = "@app/games/FETCH_GAMES_SUCCESS";
const FETCH_GAMES_FAILURE = "@app/games/FETCH_GAMES_FAILURE";

export const gamesTypes = {
  CREATE_GAME_REQUEST,
  CREATE_GAME_SUCCESS,
  CREATE_GAME_FAILURE,

  FETCH_GAMES_SUCCESS,
  FETCH_GAMES_REQUEST,
  FETCH_GAMES_FAILURE
};
