const CREATE_GAME_REQUEST = "@app/games/CREATE_GAME_REQUEST";
const CREATE_GAME_SUCCESS = "@app/games/CREATE_GAME_SUCCESS";
const CREATE_GAME_FAILURE = "@app/games/CREATE_GAME_FAILURE";

const FETCH_GAMES_SUCCESS = "@app/games/FETCH_GAMES_SUCCESS";

export const gamesTypes = {
  CREATE_GAME_REQUEST,
  CREATE_GAME_SUCCESS,
  CREATE_GAME_FAILURE,

  FETCH_GAMES_SUCCESS
};
